title: 'Manon de Groot-van Gelder — Stemactrice, Storytelling Expert, Theatermaker en Trainer'
default_lang: ned
author:
  name: 'Manon de Groot- van Gelder'
  email: manonvangelder@gmail.com
taxonomies:
  - category
  - tag
metadata:
  description: 'Manon de Groot-van Gelder — Stemactrice, Storytelling Expert, Theatermaker en Trainer'
  keywords: 'stemactrice, voiceover, theater, trainer'
summary:
  enabled: true
  format: short
  size: 300
  delimiter: '==='
redirects: null
routes: null
blog:
  route: /blog
