name: SSH deployment from repo to staging site
on: push
jobs:
  staging-deploy:
    name: Deploy to staging
    runs-on: ubuntu-latest
    if: github.ref == 'refs/heads/staging'
    steps:
    - name: Get latest code
      uses: actions/checkout@v3
    - name: Deploy to server
      uses: easingthemes/ssh-deploy@main
      env:
          SSH_PRIVATE_KEY: ${{ secrets.DEPLOY_PRIVATE_KEY }}
          ARGS: "-rlgoDzvc -i"
          SOURCE: "/"
          REMOTE_HOST: ${{ secrets.REMOTE_HOST }}
          REMOTE_USER: ${{ secrets.FTP_USERNAME }}
          REMOTE_PORT: '7685'
          TARGET: ${{ secrets.REMOTE_TARGET_STAGING }}
          EXCLUDE: ""
  live-deploy:
    name: Deploy to live
    runs-on: ubuntu-latest
    if: github.ref == 'refs/heads/master'
    steps:
    - name: Get latest code
      uses: actions/checkout@v3
    - name: Deploy to server
      uses: easingthemes/ssh-deploy@main
      env:
          SSH_PRIVATE_KEY: ${{ secrets.DEPLOY_PRIVATE_KEY }}
          ARGS: "-rlgoDzvc -i"
          SOURCE: "/"
          REMOTE_HOST: ${{ secrets.REMOTE_HOST }}
          REMOTE_USER: ${{ secrets.FTP_USERNAME }}
          REMOTE_PORT: '7685'
          TARGET: ${{ secrets.REMOTE_TARGET }}
          EXCLUDE: ""


